Repository antiquers/theAntiquersRoom, pull requests merged in 2021-11, with the labels that each got.

#2 Add README file
  README.md
Labels: documentation

#12 login, logout 기능 구현
  src/main/java/com/theantiquersroom/myapp/controller/UserController.java
  src/main/java/com/theantiquersroom/myapp/domain/UserVO.java
  src/main/java/com/theantiquersroom/myapp/mapper/UserMapper.java
  src/main/java/com/theantiquersroom/myapp/service/UserService.java
  src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/UserMapper.xml
  src/main/webapp/WEB-INF/views/main.jsp
Labels: backend :back:

#15 Beomsookim reset pwd
  .classpath
  .gitignore
  .project
  .settings/org.eclipse.core.resources.prefs
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.jst.jsp.core.prefs
  .settings/org.eclipse.m2e.core.prefs
  .settings/org.eclipse.m2e.wtp.prefs
  .settings/org.eclipse.wst.common.component
  .settings/org.eclipse.wst.common.project.facet.core.xml
  .settings/org.eclipse.wst.css.core.prefs
  .settings/org.eclipse.wst.html.core.prefs
  .settings/org.eclipse.wst.validation.prefs
  .settings/org.eclipse.wst.ws.service.policy.prefs
  .settings/org.springframework.ide.eclipse.beans.core.prefs
  .settings/org.springframework.ide.eclipse.core.prefs
  .settings/org.springframework.ide.eclipse.maven.prefs
  .springBeans
  src/main/java/com/theantiquersroom/myapp/config/MailConfig.java
  src/main/java/com/theantiquersroom/myapp/controller/UserController.java
  src/main/java/com/theantiquersroom/myapp/mapper/UserMapper.java
  src/main/java/com/theantiquersroom/myapp/service/UserService.java
  src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
  src/main/java/com/theantiquersroom/myapp/utils/Mailsender.java
  src/main/resources/com/theantiquersroom/myapp/mapper/UserMapper.xml
  src/main/resources/log4j2.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/users/resetPwd.jsp
  src/main/webapp/WEB-INF/web.xml
Labels: backend :back:, frontend :arrow_forward:

#19 kakao api front 기능 구현
  .gitignore
  src/main/java/com/theantiquersroom/myapp/controller/ApiKakaoController.java
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/login.jsp
  src/main/webapp/resources/images/kakao_login.png
  src/test/resources/log4j2.xml
Labels: frontend :arrow_forward:

#22 회원가입 API 구현
  src/main/java/com/theantiquersroom/myapp/controller/UserController.java
  src/main/java/com/theantiquersroom/myapp/domain/UserDTO.java
  src/main/java/com/theantiquersroom/myapp/mapper/UserMapper.java
  src/main/java/com/theantiquersroom/myapp/service/UserService.java
  src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/UserMapper.xml
Labels: backend :back:

#29 회원 정보, 회원 수정
  src/main/java/com/theantiquersroom/myapp/controller/UserController.java
  src/main/java/com/theantiquersroom/myapp/mapper/UserMapper.java
  src/main/java/com/theantiquersroom/myapp/service/UserService.java
  src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
  src/main/webapp/WEB-INF/views/users/get.jsp
  src/main/webapp/WEB-INF/views/users/getUserList.jsp
  src/main/webapp/WEB-INF/views/users/modify.jsp
Labels: backend :back:

#31 Ggujin security password
  pom.xml
  src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/test/java/com/theantiquersroom/myapp/pwhash/PasswordEncryptionTests.java
Labels: backend :back:

#40 kakao login api
  pom.xml
  src/main/java/com/theantiquersroom/myapp/controller/ApiKakaoController.java
  src/main/java/com/theantiquersroom/myapp/controller/UserController.java
  src/main/java/com/theantiquersroom/myapp/domain/KakaoAccountVO.java
  src/main/java/com/theantiquersroom/myapp/domain/KakaoTokenVO.java
  src/main/java/com/theantiquersroom/myapp/domain/KakaoUserInfoVO.java
  src/main/java/com/theantiquersroom/myapp/domain/UserDTO.java
  src/main/java/com/theantiquersroom/myapp/domain/UserVO.java
  src/main/java/com/theantiquersroom/myapp/mapper/UserMapper.java
  src/main/java/com/theantiquersroom/myapp/service/UserService.java
  src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/UserMapper.xml
  src/main/webapp/WEB-INF/views/home.jsp
Labels: backend :back:

#41 아이디 찾기 , 회원삭제
  src/main/java/com/theantiquersroom/myapp/controller/UserController.java
  src/main/java/com/theantiquersroom/myapp/mapper/UserMapper.java
  src/main/java/com/theantiquersroom/myapp/service/UserService.java
  src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/UserMapper.xml
  src/main/webapp/WEB-INF/views/users/findId.jsp
  src/main/webapp/WEB-INF/views/users/modify.jsp
Labels: backend :back:

#46 add login page
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/users/login.jsp
  src/main/webapp/resources/css/login.css
  src/main/webapp/resources/images/flowerBack.jpg
  src/main/webapp/resources/images/logoImg.png
Labels: frontend :arrow_forward:

#47 update loginPage
  src/main/webapp/WEB-INF/views/users/login.jsp
  src/main/webapp/resources/css/login.css
Labels: frontend :arrow_forward:

#51 UserType Enum 생성
  src/main/java/com/theantiquersroom/myapp/controller/UserController.java
  src/main/java/com/theantiquersroom/myapp/service/UserService.java
  src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
  src/main/java/com/theantiquersroom/myapp/utils/UserType.java
  src/main/webapp/WEB-INF/views/home.jsp
Labels: backend :back:

#101 BoardQnA 다시 올립니다.
  src/main/java/com/theantiquersroom/myapp/controller/BoardController.java
  src/main/java/com/theantiquersroom/myapp/domain/QnADTO.java
  src/main/java/com/theantiquersroom/myapp/mapper/BoardMapper.java
  src/main/java/com/theantiquersroom/myapp/service/BoardService.java
  src/main/java/com/theantiquersroom/myapp/service/BoardServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/BoardMapper.xml
  src/main/webapp/WEB-INF/views/board/QnA.jsp
  src/main/webapp/WEB-INF/views/board/registerQnA.jsp
Labels: backend :back:, frontend :arrow_forward:

#106 boardQnA 페이징처리
  src/main/java/com/theantiquersroom/myapp/controller/BoardController.java
  src/main/java/com/theantiquersroom/myapp/domain/BoardQnACriteria.java
  src/main/java/com/theantiquersroom/myapp/domain/QnAPageMakeDTO.java
  src/main/java/com/theantiquersroom/myapp/mapper/BoardMapper.java
  src/main/java/com/theantiquersroom/myapp/service/BoardService.java
  src/main/java/com/theantiquersroom/myapp/service/BoardServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/BoardMapper.xml
  src/main/webapp/WEB-INF/views/board/QnA.jsp
  src/main/webapp/WEB-INF/views/board/registerQnA.jsp
  src/main/webapp/resources/css/QnA.css
  src/main/webapp/resources/css/registerQnA.css
  src/test/java/com/theantiquersroom/myapp/mapper/BoardMapperTests.java
  src/test/java/com/theantiquersroom/myapp/service/BoardServiceTests.java
Labels: backend :back:

#105 update main page & header/footer of css
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/resources/css/footer.css
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/main.css
  src/main/webapp/resources/js/main.js
Labels: frontend :arrow_forward:

#114 어드민 메인(헤더), 승인요청페이지 구현 완료
  src/main/java/com/theantiquersroom/myapp/controller/AdminController.java
  src/main/java/com/theantiquersroom/myapp/controller/ApiKakaoController.java
  src/main/java/com/theantiquersroom/myapp/controller/LoginController.java
  src/main/java/com/theantiquersroom/myapp/interceptor/LoginInterceptor.java
  src/main/java/com/theantiquersroom/myapp/mapper/AdminMapper.java
  src/main/java/com/theantiquersroom/myapp/service/AdminService.java
  src/main/java/com/theantiquersroom/myapp/service/AdminServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/AdminMapper.xml
  src/main/webapp/WEB-INF/views/admin/requestedList.jsp
  src/main/webapp/WEB-INF/views/common/adminHeader.jsp
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/users/myAuctionList.jsp
  src/main/webapp/resources/css/adminHeader.css
  src/main/webapp/resources/css/myAuctionList.css
Labels: backend :back:, frontend :arrow_forward:

#115 add GetProductImageUrls() into getDetail & update detailPage
  src/main/java/com/theantiquersroom/myapp/domain/ProductDTO.java
  src/main/java/com/theantiquersroom/myapp/mapper/ProductMapper.java
  src/main/java/com/theantiquersroom/myapp/service/ProductServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
  src/main/webapp/WEB-INF/views/detail.jsp
  src/test/java/com/theantiquersroom/myapp/mapper/ProductMapperTests.java
  src/test/java/com/theantiquersroom/myapp/service/ProductServiceTests.java
Labels: backend :back:

#119 BoardQnA(계층형 미완)
  src/main/java/com/theantiquersroom/myapp/controller/BoardController.java
  src/main/java/com/theantiquersroom/myapp/domain/QnADTO.java
  src/main/java/com/theantiquersroom/myapp/mapper/BoardMapper.java
  src/main/java/com/theantiquersroom/myapp/service/BoardService.java
  src/main/java/com/theantiquersroom/myapp/service/BoardServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/BoardMapper.xml
  src/main/webapp/WEB-INF/views/board/QnA.jsp
  src/main/webapp/WEB-INF/views/board/getQnADetail.jsp
  src/main/webapp/WEB-INF/views/board/modifyQnA.jsp
  src/main/webapp/resources/css/getQnADetail.css
  src/test/java/com/theantiquersroom/myapp/mapper/BoardMapperTests.java
  src/test/java/com/theantiquersroom/myapp/service/BoardServiceTests.java
Labels: backend :back:

#120 review 페이지 뷰단 구현
  src/main/webapp/WEB-INF/views/board/registerReview.jsp
  src/main/webapp/WEB-INF/views/board/review.jsp
  src/main/webapp/WEB-INF/views/register.jsp
  src/main/webapp/resources/css/registerReview.css
  src/main/webapp/resources/css/review.css
  src/main/webapp/resources/images/charlie.jpeg
Labels: frontend :arrow_forward:

#121 myPageHeader, header font
  src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
  src/main/webapp/WEB-INF/views/common/mypageHeader.jsp
  src/main/webapp/WEB-INF/views/users/mypage.jsp
  src/main/webapp/resources/css/mypage.css
  src/main/webapp/resources/css/mypageHeader.css
  src/main/webapp/resources/font/ONE Mobile Title.ttf
Labels: frontend :arrow_forward:

#122 Hayoung update detail page
  src/main/webapp/WEB-INF/views/common/footer.jsp
  src/main/webapp/WEB-INF/views/detail.jsp
  src/main/webapp/resources/css/detail.css
Labels: frontend :arrow_forward:

#123 product register view add
  src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
  src/main/webapp/WEB-INF/views/product/register.jsp
  src/main/webapp/resources/css/datetimepicker/jquery.datetimepicker.min.css
  src/main/webapp/resources/css/product/register.css
  src/main/webapp/resources/js/datetimepicker/jquery.datetimepicker.full.min.js
Labels: frontend :arrow_forward:

#127 승인요청 반려 기능 추가 구현
  src/main/java/com/theantiquersroom/myapp/controller/AdminController.java
  src/main/java/com/theantiquersroom/myapp/domain/ProductDTO.java
  src/main/java/com/theantiquersroom/myapp/mapper/AdminMapper.java
  src/main/java/com/theantiquersroom/myapp/service/AdminService.java
  src/main/java/com/theantiquersroom/myapp/service/AdminServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/AdminMapper.xml
  src/main/resources/com/theantiquersroom/myapp/mapper/UserMapper.xml
  src/main/webapp/WEB-INF/views/admin/requestedList.jsp
  src/main/webapp/WEB-INF/views/common/footer.jsp
  src/main/webapp/WEB-INF/views/users/myAuctionList.jsp
  src/main/webapp/resources/css/footer.css
  src/main/webapp/resources/css/myAuctionList.css
Labels: backend :back:, frontend :arrow_forward:

#135 add AdminUserList
  src/main/java/com/theantiquersroom/myapp/HomeController.java
  src/main/java/com/theantiquersroom/myapp/controller/AdminController.java
  src/main/java/com/theantiquersroom/myapp/domain/UserVO.java
  src/main/java/com/theantiquersroom/myapp/mapper/AdminMapper.java
  src/main/java/com/theantiquersroom/myapp/mapper/UserMapper.java
  src/main/java/com/theantiquersroom/myapp/service/AdminService.java
  src/main/java/com/theantiquersroom/myapp/service/AdminServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/AdminMapper.xml
  src/main/webapp/WEB-INF/views/admin/userList.jsp
  src/main/webapp/WEB-INF/views/common/adminHeader.jsp
  src/main/webapp/resources/css/adminHeader.css
  src/main/webapp/resources/css/userList.css
  src/main/webapp/resources/js/userList.js
  src/test/java/com/theantiquersroom/myapp/mapper/AdminMapperTests.java
  src/test/java/com/theantiquersroom/myapp/service/AdminServiceTests.java
Labels: backend :back:, frontend :arrow_forward:

#136 product modify API
  src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
  src/main/java/com/theantiquersroom/myapp/domain/ProductModifyDTO.java
  src/main/java/com/theantiquersroom/myapp/mapper/ImageMapper.java
  src/main/java/com/theantiquersroom/myapp/mapper/ProductMapper.java
  src/main/java/com/theantiquersroom/myapp/service/ProductService.java
  src/main/java/com/theantiquersroom/myapp/service/ProductServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/ImageMapper.xml
  src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
  src/main/webapp/WEB-INF/views/product/modify.jsp
  src/main/webapp/resources/css/product/modify.css
  src/test/java/com/theantiquersroom/myapp/mapper/ProductMapperTests.java
  src/test/java/com/theantiquersroom/myapp/service/ProductServiceTests.java
Labels: backend :back:, frontend :arrow_forward:

#138 어드민 경매상품 키워드 검색 기능 구현
  src/main/java/com/theantiquersroom/myapp/controller/AdminController.java
  src/main/java/com/theantiquersroom/myapp/domain/MypageCriteria.java
  src/main/java/com/theantiquersroom/myapp/mapper/AdminMapper.java
  src/main/java/com/theantiquersroom/myapp/service/AdminService.java
  src/main/java/com/theantiquersroom/myapp/service/AdminServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/AdminMapper.xml
  src/main/webapp/WEB-INF/views/admin/auctionProductList.jsp
  src/main/webapp/WEB-INF/views/common/adminHeader.jsp
  src/main/webapp/resources/css/myAuctionList.css
Labels: backend :back:, frontend :arrow_forward:

#140 update result view of searchUser()
  src/main/webapp/WEB-INF/views/admin/userList.jsp
  src/main/webapp/resources/css/userList.css
Labels: frontend :arrow_forward:

#141 update login interceptor for admin login
  src/main/java/com/theantiquersroom/myapp/controller/LoginController.java
  src/main/java/com/theantiquersroom/myapp/controller/UserController.java
  src/main/java/com/theantiquersroom/myapp/interceptor/LoginInterceptor.java
Labels: backend :back:

#142 update mypage UI
  src/main/webapp/WEB-INF/views/users/mypage.jsp
  src/main/webapp/resources/css/mypage.css
Labels: frontend :arrow_forward:

#143 product modify view 파일업로드, 레이아웃 수정
  src/main/webapp/WEB-INF/views/product/modify.jsp
  src/main/webapp/resources/css/product/modify.css
Labels: frontend :arrow_forward:

#144 관리자 경매상품 필터 기능 구현
  src/main/java/com/theantiquersroom/myapp/controller/AdminController.java
  src/main/java/com/theantiquersroom/myapp/controller/UserController.java
  src/main/java/com/theantiquersroom/myapp/domain/MypageCriteria.java
  src/main/java/com/theantiquersroom/myapp/mapper/AdminMapper.java
  src/main/java/com/theantiquersroom/myapp/service/AdminService.java
  src/main/java/com/theantiquersroom/myapp/service/AdminServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/AdminMapper.xml
  src/main/webapp/WEB-INF/views/admin/auctionProductList.jsp
  src/main/webapp/WEB-INF/views/registerByKakao.jsp
Labels: backend :back:, frontend :arrow_forward:

#145 product reRegister API 구현
  src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
  src/main/java/com/theantiquersroom/myapp/domain/ProductReRegisterDTO.java
  src/main/java/com/theantiquersroom/myapp/mapper/ProductMapper.java
  src/main/java/com/theantiquersroom/myapp/service/ProductService.java
  src/main/java/com/theantiquersroom/myapp/service/ProductServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
Labels: backend :back:

#147 Bb update status
  src/main/java/com/theantiquersroom/myapp/utils/AuctionStatus.java
  src/main/java/com/theantiquersroom/myapp/utils/UserType.java
  src/main/webapp/WEB-INF/views/admin/auctionProductList.jsp
Labels: frontend :arrow_forward:, 수정

#149 상품삭제오류수정
  src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
  src/main/java/com/theantiquersroom/myapp/controller/UserController.java
Labels: bug, frontend :arrow_forward:, DB

#156 Exception API 구현, 간단한 test view
  src/main/java/com/theantiquersroom/myapp/Eception/CommonExceptionAdvice.java
  src/main/webapp/WEB-INF/views/error/errorPage.jsp
Labels: backend :back:

#158 add SweetAlert2(in footer), update UserRegister UI
  src/main/webapp/WEB-INF/views/common/footer.jsp
  src/main/webapp/WEB-INF/views/register.jsp
  src/main/webapp/resources/css/footer.css
  src/main/webapp/resources/css/register.css
  src/main/webapp/resources/js/registerCheck.js
Labels: frontend :arrow_forward:

#166 종료된 상품 화면 출력 하지않도록 수정
  src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
  src/main/webapp/WEB-INF/views/main.jsp
Labels: backend :back:

#165 #162 issue_update bidBtn event in detail page
  src/main/webapp/WEB-INF/views/detail.jsp
  src/main/webapp/resources/css/detail.css
  src/main/webapp/resources/css/footer.css
Labels: frontend :arrow_forward:

#168 카테고리명과 화면이 일치하지 않는 이슈 해결
  src/main/webapp/WEB-INF/views/product/productList.jsp
Labels: frontend :arrow_forward:

#171 change main Banner img
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/resources/css/main.css
Labels: frontend :arrow_forward:

#172 fix productList page_change to Grid
  src/main/webapp/WEB-INF/views/product/productList.jsp
  src/main/webapp/resources/css/main.css
  src/main/webapp/resources/css/productList.css
Labels: frontend :arrow_forward:

#176 어드민 상품목록 디테일 버그수정
  src/main/webapp/WEB-INF/views/admin/auctionProductList.jsp
  src/main/webapp/WEB-INF/views/admin/requestedList.jsp
  src/main/webapp/resources/css/myAuctionList.css
Labels: bug, frontend :arrow_forward:

#178 SeachBar Change, ProductCriteria Modify 9 >> 12
  src/main/java/com/theantiquersroom/myapp/domain/ProductCriteria.java
  src/main/webapp/resources/css/header.css
Labels: frontend :arrow_forward:

#182 #181 이슈 참조
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/resources/css/footer.css
  src/main/webapp/resources/js/registerCheck.js
Labels: frontend :arrow_forward:

#184 fix registerCheck, BoardController
  src/main/java/com/theantiquersroom/myapp/controller/BoardController.java
  src/main/webapp/WEB-INF/views/register.jsp
  src/main/webapp/resources/js/registerCheck.js
Labels: frontend :arrow_forward:

#185 delete log, fix modify_User UI
  src/main/java/com/theantiquersroom/myapp/controller/LoginController.java
  src/main/java/com/theantiquersroom/myapp/controller/UserController.java
  src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
  src/main/webapp/WEB-INF/views/users/modify.jsp
  src/main/webapp/resources/css/modify.css
Labels: frontend :arrow_forward:

#187 fix #186 issue
  src/main/java/com/theantiquersroom/myapp/service/UserServiceImpl.java
Labels: backend :back:

#191 product register, modify 수정
  src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
  src/main/java/com/theantiquersroom/myapp/service/ProductServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
  src/main/webapp/WEB-INF/views/product/modify.jsp
  src/main/webapp/WEB-INF/views/product/register.jsp
Labels: backend :back:, frontend :arrow_forward:

#195 카카오 회원가입, 로그인, 로그아웃 업데이트
  src/main/java/com/theantiquersroom/myapp/controller/ApiKakaoController.java
  src/main/java/com/theantiquersroom/myapp/controller/UserController.java
  src/main/webapp/WEB-INF/views/registerByKakao.jsp
Labels: bug, backend :back:, frontend :arrow_forward:

#193 product register modify (sweet alert추가)
  src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
  src/main/webapp/WEB-INF/views/product/modify.jsp
  src/main/webapp/WEB-INF/views/product/register.jsp
Labels: frontend :arrow_forward:

#196 delete alert 띄우기
  src/main/java/com/theantiquersroom/myapp/controller/UserController.java
Labels: bug

#200 Bid
  src/main/webapp/WEB-INF/views/detail.jsp
  src/main/webapp/resources/css/detail.css
Labels: frontend :arrow_forward:

#201 product category 변경사항 적용, pid오류 -> 매퍼수정
  src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/product/modify.jsp
  src/main/webapp/WEB-INF/views/product/productList.jsp
  src/main/webapp/WEB-INF/views/product/register.jsp
Labels: backend :back:, frontend :arrow_forward:, 설계, 수정

#202 출력상품에 상품승인여부 조건 추가, 상품필터 수정
  src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
Labels: backend :back:

#208 로고 이미지 추가, 리뷰 작성, 리뷰 등록, 긴 글 리뷰 토글기능
  src/main/java/com/theantiquersroom/myapp/controller/BoardController.java
  src/main/java/com/theantiquersroom/myapp/domain/ReviewDTO.java
  src/main/resources/com/theantiquersroom/myapp/mapper/BoardMapper.xml
  src/main/webapp/WEB-INF/views/board/registerReview.jsp
  src/main/webapp/WEB-INF/views/board/review.jsp
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/detail.jsp
  src/main/webapp/resources/css/registerReview.css
  src/main/webapp/resources/css/review.css
  src/main/webapp/resources/images/logo6.png
Labels: backend :back:

#210 update Review page UI
  src/main/webapp/WEB-INF/views/board/review.jsp
  src/main/webapp/resources/css/myAuctionList.css
  src/main/webapp/resources/css/review.css
Labels: frontend :arrow_forward:

#212 update QnA list page UI
  src/main/webapp/WEB-INF/views/board/QnA.jsp
  src/main/webapp/resources/css/QnA.css
  src/main/webapp/resources/css/review.css
Labels: frontend :arrow_forward:
