Repository antiquers/theAntiquersRoom, pull requests merged in 2021-12, with the labels that each got.

#211 mybidList -> 리뷰작성 path 수정
  src/main/webapp/WEB-INF/views/users/myBidList.jsp
Labels: backend :back:

#214 Admin Sweet Alert2
  src/main/java/com/theantiquersroom/myapp/controller/AdminController.java
  src/main/webapp/WEB-INF/views/admin/auctionProductList.jsp
  src/main/webapp/WEB-INF/views/admin/requestedList.jsp
  src/main/webapp/resources/css/footer.css
Labels: frontend :arrow_forward:

#215 BoardQnA
  src/main/webapp/WEB-INF/views/board/QnA.jsp
  src/main/webapp/WEB-INF/views/board/getQnADetail.jsp
  src/main/webapp/WEB-INF/views/board/modifyQnA.jsp
  src/main/webapp/WEB-INF/views/board/registerQnA.jsp
  src/main/webapp/WEB-INF/views/board/registerReQnA.jsp
Labels: frontend :arrow_forward:

#224 pId -> pid 변경, 회원가입 button 변경, 상품 등록,수정 경로 변경
  src/main/java/com/theantiquersroom/myapp/controller/AdminController.java
  src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
  src/main/resources/com/theantiquersroom/myapp/mapper/AdminMapper.xml
  src/main/webapp/WEB-INF/views/product/modify.jsp
  src/main/webapp/WEB-INF/views/product/register.jsp
  src/main/webapp/WEB-INF/views/register.jsp
Labels: backend :back:

#226 update detail script
  src/main/webapp/WEB-INF/views/detail.jsp
Labels: frontend :arrow_forward:

#227 리뷰 쿼리문 수정
  src/main/resources/com/theantiquersroom/myapp/mapper/BoardMapper.xml
  src/main/webapp/WEB-INF/views/board/registerReview.jsp
  src/main/webapp/WEB-INF/views/board/review.jsp
Labels: backend :back:

#229 change main Banner imgs
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/resources/css/main.css
Labels: frontend :arrow_forward:

#230 쇼파 -> 소파 명칭 변경(표준어)
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/product/modify.jsp
  src/main/webapp/WEB-INF/views/product/productList.jsp
  src/main/webapp/WEB-INF/views/product/register.jsp
Labels: 수정

#231 나의옥션 판매자 chat 연결
  src/main/java/com/theantiquersroom/myapp/controller/UserController.java
  src/main/webapp/WEB-INF/views/users/chat.jsp
  src/main/webapp/WEB-INF/views/users/myAuctionList.jsp
  src/main/webapp/WEB-INF/views/users/myBidList.jsp
Labels: 수정

#232 BoardQnA 답글버튼 오류 수정
  src/main/webapp/WEB-INF/views/board/getQnADetail.jsp
Labels: frontend :arrow_forward:

#233 에러페이지 뷰단 생성
  src/main/resources/com/theantiquersroom/myapp/mapper/BoardMapper.xml
  src/main/webapp/WEB-INF/views/error/errorPage.jsp
  src/main/webapp/resources/images/errorpage.jpg
Labels: frontend :arrow_forward:

#234 판매자의 이전 리뷰 뷰페이지 수정, 쿼리수정, 리뷰페이지 이름수정
  src/main/java/com/theantiquersroom/myapp/controller/BoardController.java
  src/main/java/com/theantiquersroom/myapp/mapper/BoardMapper.java
  src/main/java/com/theantiquersroom/myapp/service/BoardService.java
  src/main/java/com/theantiquersroom/myapp/service/BoardServiceImpl.java
  src/main/resources/com/theantiquersroom/myapp/mapper/BoardMapper.xml
  src/main/webapp/WEB-INF/views/board/registerReview.jsp
  src/main/webapp/WEB-INF/views/board/review.jsp
  src/main/webapp/resources/css/registerReview.css
Labels: frontend :arrow_forward:

#235 change User pages UI
  src/main/webapp/WEB-INF/views/common/adminHeader.jsp
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/login.jsp
  src/main/webapp/WEB-INF/views/register.jsp
  src/main/webapp/WEB-INF/views/users/modify.jsp
  src/main/webapp/resources/css/adminHeader.css
  src/main/webapp/resources/css/login.css
  src/main/webapp/resources/css/modify.css
  src/main/webapp/resources/css/mypage.css
  src/main/webapp/resources/css/register.css
Labels: frontend :arrow_forward:

#236 product modify 경로 수정
  src/main/java/com/theantiquersroom/myapp/controller/ProductController.java
Labels: backend :back:

#237 sweet alert sub text removed
  src/main/webapp/WEB-INF/views/admin/requestedList.jsp
Labels: 수정

#238 Paging li 태그
  src/main/resources/com/theantiquersroom/myapp/mapper/ProductMapper.xml
  src/main/webapp/WEB-INF/views/product/productList.jsp
  src/main/webapp/resources/css/productList.css
Labels: frontend :arrow_forward:

#239 나의경매리스트 버튼명 변경, pId->pid 수정
  src/main/webapp/WEB-INF/views/users/myAuctionList.jsp
Labels: 수정
